### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by MrBlue90** [photon-wp/material-design-icons-for-elementor#10]
Dear developer,

First of all; appreciate the plugin. This allows me to be way more flexible in the choice of icons.

Though, I noticed that some icons are still missing from the plugin.
Example: https://materialdesignicons.com/icon/cctv

Am I missing something obvious, or is there a reason for (community) icons missing?

Thanks

**Comment by MrBlue90** [comment]
Nevermind.. I figured out my own stupidity.
Got to realize that there's a difference between my Material Design Icons set and Google's version (which you're using).

Though, is there any way of adding this resource to the plugin?

_In the meantime, if ppl are looking for the same, I found a script that you need to add to your functions.php file (in theme folder) and list the icons you need: https://gist.github.com/raazon/a98ef02c8a9706d4fcab4f3f8290db2b
Not perfect, but good enough for now._

**Comment by kaskad88** [comment]
Hello, @MrBlue90. You are right, we are using the Material Design Icons by Google. Unfortunately we have no plans to add icons from https://materialdesignicons.com/ yet, but anything is possible.
