### ISSUE TITLE
This zip file provided is not supported!

### ISSUE THREAD

**Issue by nicogombau** [photon-wp/material-design-icons-for-elementor#11]
![image](https://user-images.githubusercontent.com/104169541/171994802-74737d16-bca4-48aa-902f-8ddc6cde9734.png)

**Comment by kaskad88** [comment]
Material Design Icons for Page Builders is a plugin, not an icon set. 

INSTALLATION
1. Install using the WordPress built-in Plugin installer, or Extract the zip file and drop the contents in the wp-content/plugins/ directory of your WordPress installation.
2. Activate the plugin through the ‘Plugins’ menu in WordPress.
